# A example of ClusterConfig with IAMServiceAccounts:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: irp-test-4
  region: us-west-2

iam:
  withOIDC: true
  serviceAccounts: # TODO: refine naming
  - metadata:
      name: s3-reader
      # if no namespace is set, "default" will be used;
      # the namespace will be created if it doesn't exist already
      namespace: backend-apps
      labels: {aws-app-access: "true"}
      annotations: {aws-sercvices: '[ "s3/read-only" ]'}
    attachPolicyARNs:
    - "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"
  - metadata:
      name: cache-access
      namespace: backend-apps
      labels: {aws-app-access: "true"}
      annotations: {aws-services: '[ "dynamodb/read-only", "elacticache/full" ]'}
    attachPolicyARNs:
    - "arn:aws:iam::aws:policy/AmazonDynamoDBReadOnlyAccess"
    - "arn:aws:iam::aws:policy/AmazonElastiCacheFullAccess"
  - metadata:
      name: todo
      namespace: ops
      labels: {aws-ops-access: "true"}
    attachPolicy: {} # show this

nodeGroups: [{name: "ng-1", desiredCapacity: 1}]
